language: go

go:
  - "1.14"
  - tip

env:
  - GO111MODULE=on

jobs:
  include:
    - stage: test
      script: go test -cover -tags test -race -timeout 30s ./...
    - stage: vet
      script: go vet ./...
    - stage: build
      script: go build -o shorturl.o
